# Generated by Django 3.0.5 on 2020-04-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='recordingUrl',
            new_name='direction',
        ),
    ]
