# Generated by Django 3.0.5 on 2020-04-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivr', '0002_auto_20200424_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankdetails',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivr.User'),
        ),
    ]
